spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:
    url: jdbc:mysql://x.x.x.x:3306/db_demo?serverTimezone=CTT&useSSL=false&useUnicode=true&characterEncoding=utf-8
    tomcat:
      #最大连接等待超时时间
      max-wait: 10000
      #初始化连接数
      initialSize: 1
      #最大活跃数
      max-active: 30
      test-on-borrow: true
    hikari:
      minimumIdle: 20
      maximumPoolSize: 500
      idleTimeout: 120000
      connectionTimeout: 800000
      leakDetectionThreshold: 600000
  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        database-platform: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#        # 开启批量插入
#        jdbc:
#          batch_size: 500
#          batch_versioned_data: true
#        order_inserts: true
#        order_updates: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
  redis:
    host:
    port:
    password:
    timeout: 5000     #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
        test-on-create: false
        test-on-borrow: true
        test-on-return: false
        test-while-idle: true
    lettuce:
      shutdown-timeout: 0
  quartz:
    # 相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          # 线程池的参数配置
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
              # 指定监听器的类 进行属性装配，这里我添加了一个监听器的装配类
              #          plugin:
              #            runningListener:
            #              class: com.demo.core.job.plugin.RunningListenerPlugin
            # 自定义属性，代码中读取，用于控制是否开启监听
    #              enableRunningLog: true
    # 持久化-数据库方式存储
    job-store-type: jdbc
http:
  port: 8080
server:
  servlet:
    context-path: /
  tomcat:
    accept-count: 200
    max-connection: 10000
    min-spare-threads: 20
scheduler:
  0/10 * * * * ?